backend:
  name: github
  branch: master
  repo: chubbymaus/courtgarr

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: '{{slug}}'
    fields:
      - { label: "Post Title", name: "title", widget: "string" }
      - { label: "Post Slug", name: "slug", widget: "string" }
      - { label: "Post Date", name: "date", widget: "date" }
      - { label: "Post Topic", name: "topic", widget: "select", options: ["React","Nodejs","Vue","Python","Devops","Design"] }
      - { label: "Post Body", name: "body", widget: "markdown" }